# Generated by Django 4.2.13 on 2024-11-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0002_people_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='faceImg',
            field=models.ImageField(default=1, upload_to='faces/'),
            preserve_default=False,
        ),
    ]
