# Generated by Django 4.2.13 on 2024-11-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0003_people_faceimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visiting_time', models.DateTimeField(auto_now_add=True)),
                ('countOFvisits', models.IntegerField()),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='rasp.people')),
            ],
        ),
    ]
