# Generated by Django 4.2.13 on 2024-11-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0004_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='countOFvisits',
            field=models.IntegerField(default=0),
        ),
    ]
