# Generated by Django 4.2.13 on 2024-12-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0005_alter_visits_countofvisits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='faceImg',
            field=models.ImageField(upload_to='all_face'),
        ),
    ]
