# Generated by Django 4.2.13 on 2024-12-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0006_alter_people_faceimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='faceImg',
            field=models.ImageField(upload_to='all_faces'),
        ),
    ]
